[package]
name = "learnopengl"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
env_logger = "0.10"
log = "0.4"

assimp = "0.3"
assimp-sys = "0.3"
glm = "0.2"
gl = "0.14"
glfw = "0.49"
image = "0.24"