[workspace]
members = [
    "crates/opengl-sys",
    "crates/opengl",
    "crates/winman",
    "crates/playground",
    "crates/tutorials/part-1-getting-started",
    "crates/tutorials/part-2-lighting",
    "crates/tutorials/part-3-model-loading",
    "crates/tutorials/part-4-advanced-opengl",
]